### ISSUE TITLE
unable to run - npm install sqlite3-

### ISSUE THREAD

**Issue by Moamin-AbuEwaida** [HackYourFutureBelgium/class-15#347]
Hi coaches!!
I've been trying to work on the tasks of this module -Database- and managed to have a separate folder to implement sqlite3 and require it normally to run the app and it worked.
When i tried to do the same with the clowned slack app as using database to save data instead save them locally to json file as well as to database>>week1 exercises, i did the same command by running ```npm install --save sqlite3``` but I had many errors and warnings and the latest list of warnings i received was 
```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/sqlite3
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sqlite3'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/sqlite3'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/sqlite3'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hyf/.npm/_logs/2021-11-18T09_02_39_557Z-debug.log
```
i googled the code EACCES error to follow the instruction to recover such bug/error - [HERE](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)- but i started to get lost of the steps by reinstalling node and npm -which i already did-
the weird things is the separate folder where I was practice implementing sqlite3 is still working normally but the main folder of the main project -clowned slack- and database>>week1 still not able to install the sqlite3
I also installed ```@mapbox/node-pre-gyp``` was written at one of the warning lines and now it's not there anymore.
also I tried to trick the system by adding sqlite3 manually to the package.json file dependencies and try to run the file but still acting as sqlite3 module is not active!!

**Comment by Moamin-AbuEwaida** [comment]
it's looks like that I managed to solve the access issue, not when I'm running `npm install sqlite3` i'm getting new errors :grin: 
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /home/hyf/Documents/Hack-my-future-class15/10 web apps/databases/week-1/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-18T15_10_43_974Z-debug.log
```
I tried to follow the warnings instructions and points by updating the uuid version and upgrading the mapbox ... etc!! but no changes
after "trying" updating and upgrading the libraries and run the example with `node example-1 UserName Employee` as a test, i received these
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'sqlite3'
Require stack:
- /home/hyf/Documents/Hack-my-future-class15/10 web apps/databases/week-1/cli-query-scripts/example-1.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/hyf/Documents/Hack-my-future-class15/10 web apps/databases/week-1/cli-query-scripts/example-1.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/hyf/Documents/Hack-my-future-class15/10 web apps/databases/week-1/cli-query-scripts/example-1.js'
  ]
}
```

**Comment by Moamin-AbuEwaida** [comment]
solved :man_dancing:
